name: Run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports: ["5432:5432"]
        env:
          POSTGRES_PASSWORD: postgres
    steps:
    - uses: actions/checkout@v2
    - name: Setup Ruby 2.6.3
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.3
    - run: ruby -v
    - name: Cache Gems
      uses: actions/cache@v1.1.2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: ${{ runner.os }}-gems-
    - name: Build and test with Rake
      run: |
        cp config/database.github-actions.yml config/database.yml
        gem install bundler
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
        bundle exec rake db:setup
        bundle exec rake
      env:
        RAILS_ENV: test
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.APTIBLE_SSH_KEY }}
          known_hosts: ${{ secrets.APTIBLE_KNOWN_HOSTS }}
      - name: Deploy to aptible
        run: |
          ssh-keygen -R hostname
          git push git@beta.aptible.com:p-ebt/app-staging.git master
        env:
          RAILS_ENV: test
          APTIBLE_SSH_KEY: ${{ secrets.APTIBLE_SSH_KEY }}
